---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appliance-management
  namespace: appliance-management
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: appliance-management
  template:
    metadata:
      labels:
        app: appliance-management
      annotations:
        rollout-timestamp: "{{ GITHUB_SHA }}"  # This will be replaced in your GitHub Action
    spec:
      containers:
        - name: appliance-management-container
          image: stathiskap/appliance-management:1.0
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 100
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:gZRiEt9FuCLgo85@my-postgres-postgresql.postgres.svc.cluster.local:5432/postgres"
            - name: DEBUG
              value: "False"
            - name: ALLOWED_HOSTS
              value: '["appliance-management.co.uk"]'
            - name: S3_ENDPOINT_URL
              value: "https://cdn.appliance-management.co.uk"
            - name: S3_ACCESS_KEY
              value: "wO9gEaLKvtI0Nx69EYpN"
            - name: S3_SECRET_KEY
              value: "8mmFyFNQIvzF1dXOSgBXAxqj9JOA7JktJEqQBLOv"
            - name: S3_BUCKET_NAME
              value: app-manager
            - name: SUPERUSER_NAME
              value: "admin"
            - name: SUPERUSER_PASSWORD
              value: "test"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "2"
              memory: "4Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: appliance-management-service
  namespace: appliance-management
spec:
  selector:
    app: appliance-management
  ports:
    - name: api-port
      protocol: TCP
      port: 8000
      targetPort: 8000
