# Generated by Django 5.1.7 on 2025-04-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("appliance", "0001_initial"),
  ]

  operations = [
    migrations.AlterField(
      model_name="appliance",
      name="appliance_type",
      field=models.CharField(
        choices=[("Washing machine", "WASHING_MACHINE"), ("Dryer", "DRYER")],
        max_length=20,
      ),
    ),
  ]
