# Generated by Django 5.1.7 on 2025-04-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("appliance", "0002_alter_appliance_appliance_type"),
  ]

  operations = [
    migrations.AddField(
      model_name="appliance",
      name="usage",
      field=models.CharField(
        choices=[
          ("low", "LOW"),
          ("medium", "MEDIUM"),
          ("high", "HIGH"),
          ("very_high", "VERY_HIGH"),
        ],
        default="low",
        max_length=50,
      ),
      preserve_default=False,
    ),
  ]
