# Generated by Django 5.1.7 on 2025-04-06 18:52

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("appliance", "0003_appliance_usage"),
  ]

  operations = [
    migrations.AddField(
      model_name="appliance",
      name="purchase_date",
      field=models.DateField(default=django.utils.timezone.now),
    ),
    migrations.AddField(
      model_name="appliance",
      name="warranty_period",
      field=models.DurationField(
        default=datetime.timedelta(days=365),
        help_text="Duration of the warranty period",
      ),
    ),
  ]
