# Generated by Django 5.1.7 on 2025-04-07 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("appliance", "0004_appliance_purchase_date_appliance_warranty_period"),
  ]

  operations = [
    migrations.CreateModel(
      name="Schedule",
      fields=[
        (
          "id",
          models.BigAutoField(
            auto_created=True,
            primary_key=True,
            serialize=False,
            verbose_name="ID",
          ),
        ),
        ("date", models.DateField()),
        ("time", models.TimeField()),
        (
          "tenant_email",
          models.EmailField(blank=True, max_length=254, null=True),
        ),
        (
          "tenant_phone",
          models.CharField(blank=True, max_length=10, null=True),
        ),
        (
          "appliance",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            to="appliance.appliance",
          ),
        ),
      ],
    ),
  ]
