# Generated by Django 5.1.7 on 2025-04-07 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliance", "0005_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="property",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="appliance.property",
            ),
            preserve_default=False,
        ),
    ]
