# Generated by Django 5.1.7 on 2025-04-07 03:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliance", "0006_schedule_property"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="time",
        ),
        migrations.AddField(
            model_name="schedule",
            name="hour",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(23),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedule",
            name="minute",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(59),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedule",
            name="notifications_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="appliance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="appliance.appliance",
            ),
        ),
    ]
