# Generated by Django 5.1.7 on 2025-04-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "appliance",
            "0007_remove_schedule_time_schedule_hour_schedule_minute_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="tenant_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
