# Generated by Django 5.1.7 on 2025-04-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliance", "0008_alter_schedule_tenant_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appliance",
            name="appliance_type",
            field=models.CharField(
                choices=[("WASHING_MACHINE", "Washing machine"), ("DRYER", "Dryer")],
                max_length=20,
            ),
        ),
    ]
