# Generated by Django 5.1.7 on 2025-04-07 13:23

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliance", "0009_alter_appliance_appliance_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appliance",
            name="matching_score",
        ),
        migrations.RemoveField(
            model_name="appliance",
            name="purchase_date",
        ),
        migrations.RemoveField(
            model_name="appliance",
            name="usage",
        ),
        migrations.RemoveField(
            model_name="property",
            name="appliances",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="appliance",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="property",
        ),
        migrations.AlterField(
            model_name="appliance",
            name="warranty_period",
            field=models.DurationField(
                default=datetime.timedelta(days=365),
                help_text="Default duration of the warranty period",
            ),
        ),
        migrations.CreateModel(
            name="PropertyAppliance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_date", models.DateField(default=django.utils.timezone.now)),
                ("actual_cost", models.IntegerField(blank=True, null=True)),
                (
                    "actual_warranty_period",
                    models.DurationField(
                        blank=True,
                        help_text="Actual warranty period for this specific purchase",
                        null=True,
                    ),
                ),
                (
                    "usage",
                    models.CharField(
                        choices=[
                            ("low", "LOW"),
                            ("medium", "MEDIUM"),
                            ("high", "HIGH"),
                            ("very_high", "VERY_HIGH"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "matching_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                (
                    "appliance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appliance_properties",
                        to="appliance.appliance",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_appliances",
                        to="appliance.property",
                    ),
                ),
            ],
            options={
                "unique_together": {("property", "appliance")},
            },
        ),
        migrations.AddField(
            model_name="schedule",
            name="property_appliance",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="appliance.propertyappliance",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="UserProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landlords",
                        to="appliance.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "property")},
            },
        ),
    ]
