# Generated by Django 5.1.7 on 2025-04-07 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliance", "0011_remove_propertyappliance_matching_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="replacement_appliance",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replacement_schedules",
                to="appliance.appliance",
            ),
            preserve_default=False,
        ),
    ]
