# Generated by Django 5.1.7 on 2025-04-07 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliance", "0012_schedule_replacement_appliance"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="property_pictures/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "webp",
                            "avif",
                            "heic",
                            "heif",
                            "tiff",
                            "bmp",
                        ]
                    )
                ],
            ),
        ),
    ]
