# Generated by Django 5.1.7 on 2025-04-07 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appliance", "0013_property_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="propertyappliance",
            unique_together=set(),
        ),
    ]
