# Generated by Django 5.1.7 on 2025-04-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliance", "0014_alter_propertyappliance_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appliance",
            name="appliance_type",
            field=models.CharField(
                choices=[
                    ("WASHING_MACHINE", "Washing machine"),
                    ("DISHWASHER", "Dishwasher"),
                    ("DRYER", "Dryer"),
                    ("OVEN", "Oven"),
                    ("MICROWAVE", "Microwave"),
                    ("REFRIGERATOR", "Refrigerator"),
                    ("FREEZER", "Freezer"),
                    ("TOASTER", "Toaster"),
                    ("TOASTER_OVEN", "Toaster oven"),
                ],
                max_length=20,
            ),
        ),
    ]
