# Generated by Django 5.1.7 on 2025-04-08 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliance", "0015_alter_appliance_appliance_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appliance",
            name="matching_score",
        ),
        migrations.AddField(
            model_name="propertyappliance",
            name="matching_score",
            field=models.FloatField(
                default=0.98,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
            preserve_default=False,
        ),
    ]
