# Generated by Django 5.1.7 on 2025-04-08 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliance", "0016_remove_appliance_matching_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyappliance",
            name="matching_score",
            field=models.FloatField(
                blank=True,
                default=0.0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
    ]
