# Generated by Django 5.1.7 on 2025-04-08 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appliance", "0017_alter_propertyappliance_matching_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertyappliance",
            name="matching_score",
        ),
        migrations.AddField(
            model_name="appliance",
            name="matching_score",
            field=models.FloatField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
            preserve_default=False,
        ),
    ]
