name: Build, Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        id: docker_build
        run: |
          export DOCKER_BUILDKIT=1
          docker build -t stathiskap/appliance-management:1.0 .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
          docker push stathiskap/appliance-management:1.0


  deploy:
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Configure Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml

      - name: Deploy to K3s
        run: |
          export KUBECONFIG=kubeconfig.yaml
          sed -i "s/{{ GITHUB_SHA }}/$GITHUB_SHA/g" k3s/www/django-app/django-app-deployment.yaml
          kubectl apply -f k3s/www/django-app/django-app-deployment.yaml
